apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials ## Make sure this matches the same envFrom you put in the argocd-repo-server deployment
  namespace: argocd
type: Opaque
stringData:
  VAULT_ADDR: http://vault.vault:8200 ## Your vault address You can find this by running the command 'env' inside your vault pod and find VAULT_CLUSTER_ADDR=
  AVP_TYPE: vault
  AVP_AUTH_TYPE: approle
  AVP_ROLE_ID: a4842d85-877b-f9e8-5802-ff24e27e46b8 ## The role_id you copied earlier
  AVP_SECRET_ID: 8d0aa773-ebf5-a472-e361-2f0d57ebe97e ## The secret_id you copied earlier
